### PR TITLE
feat(account page): update user full name

### LINKED ISSUE #28: Account Details Update Buttons
# Feature request

The account details page is set up to imply that you can update your account. Entry forms and buttons that actually update these things in the database would be nice.

## Describe the solution you'd like

An example of updating the name (so I can implement the email update), or full implementation by default. 

## Describe alternatives you've considered

Currently going to try to write it myself based on the handleSignUp logic.

## Additional context

Upon a local implementation and initial signup - the Full Name didn't get added to the database. When I went to manually do it in account details, there's no buttons - thus the request.

Thanks for the starter and the project. Solves some serious headaches and is very very cool.

### PR DESCRIPTION
**Pull request by irvile**
## Feature

This feature was request in this issue #28

https://user-images.githubusercontent.com/1596614/160174916-ee6d9b5a-25da-47f3-9cfb-c3e72625961e.mov

Closes #28 

Could you review this PR? @leerob @thorwebdev

### CODE REVIEW

**Comment by irvile** [comment]
Hi @tdeitz , I dont get this error. This error show when call a function and pass it a parameter that doesn't match any of its specified overloads.

I will update my branch to solve these conflicts, they updated supabase dependencies.
Hope help you.

**Comment by tdeitz** [comment]
@irvile thanks very much for the reply. I'm a Typescript amateur (at best), so my debugging ability is pretty limited for now. Appreciate the branch update, thanks again :)

**Comment by irvile** [comment]
@tdeitz done! This error that you commented show up because the new version of supabase v2, don't accept Type as the last version( `supabase.from<UserDetails>`)

Welcome! Its a pleasure help. Let me know if you have any other issue. I tested right now and supabase and stripe works fine.

**Comment by tdeitz** [comment]
@irvile thanks so much, really appreciate your efforts, can't wait to have a look! :)

**Comment by adrientiburce** [comment]
Hello,
is there any blocker for this PR to be merged ?

**Pull request closed without merging**
