### PR TITLE
feat: bump all deps to latest and fix all breaking changes

### PR DESCRIPTION
**Pull request by nezdemkovski**
Hey! I've done a bit of modernization here:
- updated to next.js 13 (no `app`, still `pages`) and some v13 fixes
- updated all libs related to supabase and fixed all deprecated functions
- migrated to pnpm

Cheers,
Yuri

### CODE REVIEW

**Review by thorwebdev — CHANGES_REQUESTED** [review]
This is awesome, thank you so much.

One thing, with updating `stirpe-node` we'll need to update the stripe API version being used. See when running `pnpm run build`:

```txt
./utils/stripe.ts:5:3
Type error: Type '"2020-08-27"' is not assignable to type '"2022-11-15"'.

  3 | export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY_LIVE ?? process.env.STRIPE_SECRET_KEY ?? '', {
  4 |   // https://github.com/stripe/stripe-node#configuration
> 5 |   apiVersion: '2020-08-27',
    |   ^
  6 |   // Register this as an official Stripe plugin.
  7 |   // https://stripe.com/docs/building-plugins#setappinfo
  8 |   appInfo: {
 ELIFECYCLE  Command failed with exit code 1.
```

Would you be able to take a look and check if there's any type changes? Thanks 💚

**Comment by thorwebdev** [comment]
Also, I'd like to send you some swag as a thank you! Will send you a DM on Twitter 👍

**Comment by nezdemkovski** [comment]
@thorwebdev yeah, you are right, I missed that stripe api version. Thanks for super quick reaction!

Now everything should build without issue. It appears that only one new stripe subscription status has been added (paused). I ran the `pnpm supabase gen types typescript --local` command, so the supabase types should now be up-to-date as well.

**Review by thorwebdev — APPROVED** [review]
This is awesome, thanks so much! 💚

**Pull request merged**
